name: ci

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: get-date
      run: echo "::set-output name=date::$(/bin/date -u "+%Y%W")"
      shell: bash

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ github.workflow }}-${{ github.job }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('Cargo.toml') }}

    - run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: get-date
      run: echo "::set-output name=date::$(/bin/date -u "+%Y%W")"
      shell: bash

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ github.workflow }}-${{ github.job }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('Cargo.toml') }}

    - run: cargo fmt --all -- --check

    - run: cargo clippy -- -D warnings
