name: test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Checking style with fmt
      run: cargo fmt --all -- --check

    - name: Linting with Clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose
